name: CI/CD Pipeline

on:
  push:
    branches:
      - homework
  pull_request:
    branches:
      - develop

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --only main
          poetry install --only dev

      - name: Run linting
        run: poetry run flake8

      - name: Run tests
        run: poetry run pytest -v

  docker-build:
    runs-on: ubuntu-latest
    needs: test-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t drf_project_backend -f Dockerfile.backend .

      - name: Build nginx Docker image
        run: docker build -t drf_project_nginx -f Dockerfile.nginx .

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Check docker compose version on server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "Проверка версии docker-compose на сервере..."
            if command -v docker-compose &> /dev/null; then
              docker-compose --version
            elif docker compose version &> /dev/null; then
              docker compose version
            else
              echo "docker-compose не найден!"
              exit 1
            fi

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.DEPLOY_DIR }}
            git pull origin develop
            # Попытка использовать modern docker compose (CLI plugin)
            if docker compose version &> /dev/null; then
              docker compose pull
              docker compose up -d --build
            else
              # fallback для старых версий
              docker-compose pull
              docker-compose up -d --build
            fi
